/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import project.*;
/**
 *
 * @author VIRAJ
 */
public class Checkout extends javax.swing.JFrame {

    /**
     * Creates new form Checkout
     */
    public Checkout() {
        initComponents();
        
        txt_name.setEditable(false);
        txt_checkInDate.setEditable(false);
        txt_CheckOutDate.setEditable(false);
        txt_MobNo.setEditable(false);
        txt_price.setEditable(false);
        txt_noOfDays.setEditable(false);
        txt_total.setEditable(false);
        txt_Email.setEditable(false);
        
    }
    int id=0;
    String Query;
    String roomtype;
    String bed;
    String roomno;
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_search = new javax.swing.JButton();
        txt_SerchRoomNo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        txt_checkInDate = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_CheckOutDate = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_MobNo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_price = new javax.swing.JTextField();
        txt_noOfDays = new javax.swing.JTextField();
        txt_total = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_Email = new javax.swing.JTextField();
        btn_checkout = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        btn_close = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(250, 100));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(926, 600));
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 255));
        jLabel1.setText("CUSTOMER CHECK OUT");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Room No");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 129, -1, -1));

        btn_search.setBackground(new java.awt.Color(0, 204, 204));
        btn_search.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btn_search.setText("Search");
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });
        getContentPane().add(btn_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(612, 124, -1, -1));
        getContentPane().add(txt_SerchRoomNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 128, 214, -1));

        Table.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Mobile No", "Nationality", "Gender", "Email", "NIC", "Address", "Check In", "Room no", "Bed type", "Room type", "Price per Day"
            }
        ));
        jScrollPane1.setViewportView(Table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 855, 147));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Customer Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 186, -1, -1));

        jLabel4.setBackground(new java.awt.Color(255, 51, 51));
        jLabel4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Check In Date");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 186, -1, -1));
        getContentPane().add(txt_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 208, 155, -1));
        getContentPane().add(txt_checkInDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 208, 155, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setText("Check Out Date (Today)");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(491, 186, -1, -1));
        getContentPane().add(txt_CheckOutDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 208, 155, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setText("Customer Mobile No");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(682, 186, -1, -1));
        getContentPane().add(txt_MobNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(655, 208, 155, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Price Per Day");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 245, -1, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel8.setForeground(java.awt.Color.white);
        jLabel8.setText("Num of Days Stayed");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 245, -1, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel9.setForeground(java.awt.Color.white);
        jLabel9.setText("Total Amount");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(515, 245, -1, -1));
        getContentPane().add(txt_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 267, 155, -1));
        getContentPane().add(txt_noOfDays, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 267, 155, -1));
        getContentPane().add(txt_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 267, 155, -1));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel10.setForeground(java.awt.Color.white);
        jLabel10.setText("E-mail");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(714, 245, -1, -1));
        getContentPane().add(txt_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(655, 267, 155, -1));

        btn_checkout.setBackground(new java.awt.Color(0, 102, 153));
        btn_checkout.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btn_checkout.setText("Check Out");
        btn_checkout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_checkoutActionPerformed(evt);
            }
        });
        getContentPane().add(btn_checkout, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 304, -1, -1));

        btn_clear.setBackground(new java.awt.Color(255, 51, 51));
        btn_clear.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btn_clear.setText("Clear");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });
        getContentPane().add(btn_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 304, 86, -1));

        btn_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel_25px.png"))); // NOI18N
        btn_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_closeActionPerformed(evt);
            }
        });
        getContentPane().add(btn_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 20, 30, 24));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/abstract-luxury-gradient-blue-background-smooth-dark-blue-withhh.jpg"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(-340, -110, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_closeActionPerformed
        setVisible(false);
        new home().setVisible(true);
    }//GEN-LAST:event_btn_closeActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO
        ResultSet rs=selectdt.getData("select*from customer where checkout is NULL");
        DefaultTableModel model=(DefaultTableModel)Table.getModel();
        try{
            while(rs.next())
            {
                model.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9),rs.getString(10),rs.getString(11),rs.getString(12),rs.getString(13)});
                
            }
            rs.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_formComponentShown

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        
        
        String roomno=txt_SerchRoomNo.getText();
        try{
            ResultSet rs=selectdt.getData("select*from customer where roomno='"+roomno+"' and checkout is NULL");
            if(rs.next())
            {
                txt_SerchRoomNo.setEditable(false);
                id=rs.getInt(1);
                txt_name.setText(rs.getString(2));
                txt_checkInDate.setText(rs.getString(9));
                txt_MobNo.setText(rs.getString(3));
                txt_price.setText(rs.getString(13));
                
                SimpleDateFormat myFormat=new SimpleDateFormat("yyyy/MM/dd");
                Calendar cal=Calendar.getInstance();
                txt_CheckOutDate.setText(myFormat.format(cal.getTime()));
                String dateBeforeString=rs.getString(9);
                java.util.Date dateBefore=myFormat.parse(dateBeforeString); //3
                String dateAfterString=myFormat.format(cal.getTime());
                java.util.Date dateAfter=myFormat.parse(dateAfterString);
                long difference=dateAfter.getTime()- dateBefore.getTime();
                int noofdaystay=(int) (difference/(1000*60*60*24));
                if(noofdaystay==0)
                    noofdaystay=1;
                    txt_noOfDays.setText(String.valueOf(noofdaystay));
                    float price=Float.parseFloat(txt_price.getText());
                    
                    txt_total.setText(String.valueOf(noofdaystay*price));
                    txt_Email.setText(rs.getString(6));
                    roomtype=rs.getString(12);
                    bed=rs.getString(11);
            }
                else
                    JOptionPane.showMessageDialog(null, "Room Number is not Booked or It does not exists");
                
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btn_searchActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        setVisible(false);
        new Checkout().setVisible(true);
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_checkoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_checkoutActionPerformed
        //
        String name=txt_name.getText();
        String mobile=txt_MobNo.getText();
        String email=txt_Email.getText();
        String checkout=txt_CheckOutDate.getText();
        String numofdays=txt_noOfDays.getText();
        String total=txt_total.getText();
        
        roomno=txt_SerchRoomNo.getText();
        
        Query="update customer set  numofdaystay='"+numofdays+"', totalamount='"+total+"',checkout='"+checkout+"' where id='"+id+"'";
        Insert_Update_Delete.setData(Query, "");
        Query="update room set status='Not Booked' where roomno='"+roomno+"'";
        Insert_Update_Delete.setData(Query, "");
        String path="E:\\";
        com.itextpdf.text.Document doc=new com.itextpdf.text.Document();
        try{
            PdfWriter.getInstance(doc, new FileOutputStream(path+""+id+".pdf"));
            doc.open();
            Paragraph paragraph1=new Paragraph("                                          ----- HOTEL MANAGEMENT SYSTEM -----                                      ");
            doc.add(paragraph1);
            Paragraph paragraph2=new Paragraph("****************************************************************************************************************");
            doc.add(paragraph2);
            Paragraph paragraph3=new Paragraph("\tBill ID: "+id+"\nCustomer Details:\nName: "+name+"\nMobile Number: "+mobile+"\nE-mail: "+email+"\n");
            doc.add(paragraph3);
            doc.add(paragraph2);
            Paragraph paragraph4=new Paragraph("\tRoom Details: \nNumber: "+txt_SerchRoomNo.getText()+"\nType: "+roomtype+"\nBed: "+bed+"\nPrice Per Day: "+txt_price.getText()+"");
            doc.add(paragraph4);
            doc.add(paragraph2);
            PdfPTable tb1=new PdfPTable(4);
            tb1.addCell("Check IN Date: "+txt_checkInDate.getText());
            tb1.addCell("Check OUT Date: "+checkout);
            tb1.addCell("No of Days Stayed: "+numofdays);
            tb1.addCell("Total Amount: "+total);
            doc.add(tb1);
            doc.add(paragraph2);
            Paragraph paragraph5=new Paragraph("                                            --__ THANK YOU,VISIT AGAIN __--                                      ");
            doc.add(paragraph5);
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        doc.close();
        int a=JOptionPane.showConfirmDialog(null, "Do you want to print a Bill", "Please select",JOptionPane.YES_NO_OPTION);
        
        if(a==0)
        {
            try
            {
                if((new File("E:\\"+id+".pdf")).exists())
                {
                    Process p =Runtime
                            .getRuntime()
                            .exec("rundll32 url.dll,FileProtocolHandler E:\\"+id+".pdf");       
                }
                else{
                    System.out.println("File is not Exists");
                }
            }
            catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
            
            setVisible(false);
            new Checkout().setVisible(true);
    }//GEN-LAST:event_btn_checkoutActionPerformed
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Checkout().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table;
    private javax.swing.JButton btn_checkout;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_close;
    private javax.swing.JButton btn_search;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_CheckOutDate;
    private javax.swing.JTextField txt_Email;
    private javax.swing.JTextField txt_MobNo;
    private javax.swing.JTextField txt_SerchRoomNo;
    private javax.swing.JTextField txt_checkInDate;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_noOfDays;
    private javax.swing.JTextField txt_price;
    private javax.swing.JTextField txt_total;
    // End of variables declaration//GEN-END:variables
}
