
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.Icon;
import project.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author VIRAJ
 */
public class customerChecking extends javax.swing.JFrame {

    /**
     * Creates new form customerChecking
     */
    public customerChecking() {
        initComponents();
        txt_checkInDate.setEditable(false);
        txt_price.setEditable(false);
        SimpleDateFormat myFormat=new SimpleDateFormat("yyyy/MM/dd");
        Calendar cal=Calendar.getInstance();
        txt_checkInDate.setText(myFormat.format(cal.getTime()));
    }
        String bed;
        String roomtype;
        String roomno;
        String price;
        
        public void roomDetails(){
            Cmb_RoomNO.removeAllItems();
            txt_price.setText("");
            bed=(String)Cmb_Btype.getSelectedItem();
            roomtype=(String)Cmb_RoomType.getSelectedItem();
            try{
                ResultSet rs=selectdt.getData("select*from room where bed='"+bed+"'and roomtype='"+roomtype+"' and status='Not Booked'");
                
                while(rs.next())
                {
                    Cmb_RoomNO.addItem(rs.getString(1));
                }
            }catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_close = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        txt_mobNo = new javax.swing.JTextField();
        txt_nationality = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        Cmb_gender = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_ID = new javax.swing.JTextField();
        txt_Addres = new javax.swing.JTextField();
        txt_checkInDate = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Cmb_Btype = new javax.swing.JComboBox<>();
        Cmb_RoomType = new javax.swing.JComboBox<>();
        Cmb_RoomNO = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        txt_price = new javax.swing.JTextField();
        btn_allteRoom = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(200, 150));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(971, 520));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CUSTOMER CHECK IN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, -1, -1));

        btn_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel_25px.png"))); // NOI18N
        btn_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_closeActionPerformed(evt);
            }
        });
        getContentPane().add(btn_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 10, 29, 24));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Mobile Number");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nationality");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Gender");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("E-mail");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 340, -1, -1));

        txt_name.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        getContentPane().add(txt_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 225, -1));

        txt_mobNo.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        getContentPane().add(txt_mobNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 225, -1));

        txt_nationality.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        getContentPane().add(txt_nationality, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 225, 25));

        txt_email.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        getContentPane().add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, 225, -1));

        Cmb_gender.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Cmb_gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));
        getContentPane().add(Cmb_gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 225, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ID Number");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, -1, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Address");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, -1, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Check In Date(Today)");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, -1, -1));

        txt_ID.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        getContentPane().add(txt_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 225, -1));

        txt_Addres.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        getContentPane().add(txt_Addres, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 225, -1));

        txt_checkInDate.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        getContentPane().add(txt_checkInDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 225, -1));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Bed Type");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 130, -1, -1));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Room No");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 260, -1, -1));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Room Type");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 190, -1, -1));

        Cmb_Btype.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Cmb_Btype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Double", "Triple" }));
        Cmb_Btype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cmb_BtypeActionPerformed(evt);
            }
        });
        getContentPane().add(Cmb_Btype, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 150, 177, -1));

        Cmb_RoomType.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Cmb_RoomType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "Non-AC" }));
        Cmb_RoomType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cmb_RoomTypeActionPerformed(evt);
            }
        });
        getContentPane().add(Cmb_RoomType, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 210, 176, -1));

        Cmb_RoomNO.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Cmb_RoomNO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cmb_RoomNOActionPerformed(evt);
            }
        });
        getContentPane().add(Cmb_RoomNO, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 280, 176, -1));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Price");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 320, -1, -1));

        txt_price.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        getContentPane().add(txt_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 340, 176, 31));

        btn_allteRoom.setBackground(new java.awt.Color(0, 102, 153));
        btn_allteRoom.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btn_allteRoom.setForeground(new java.awt.Color(51, 51, 51));
        btn_allteRoom.setText("Allot Room");
        btn_allteRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_allteRoomActionPerformed(evt);
            }
        });
        getContentPane().add(btn_allteRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 410, -1, -1));

        btn_clear.setBackground(new java.awt.Color(102, 0, 0));
        btn_clear.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btn_clear.setText("Clear");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });
        getContentPane().add(btn_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 410, 96, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/abstract-luxury-gradient-blue-background-smooth-dark-blue-with-black-vignette.jpg"))); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_closeActionPerformed
                     
        int a=JOptionPane.showConfirmDialog(null, "Are you really want to close","Select",JOptionPane.YES_NO_OPTION);
        if(a==0){
            setVisible(false);
            new home().setVisible(true);
        }
    }//GEN-LAST:event_btn_closeActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        
        setVisible(false);
        new customerChecking().setVisible(true);
    }//GEN-LAST:event_btn_clearActionPerformed

    private void Cmb_BtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cmb_BtypeActionPerformed
        //bed type combo
        roomDetails();
        
    }//GEN-LAST:event_Cmb_BtypeActionPerformed

    private void Cmb_RoomTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cmb_RoomTypeActionPerformed
        //room type combo
        roomDetails();
    }//GEN-LAST:event_Cmb_RoomTypeActionPerformed

    private void Cmb_RoomNOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cmb_RoomNOActionPerformed
        // room No combo
        
        roomno=(String)Cmb_RoomNO.getSelectedItem();
        try{
            ResultSet rs=selectdt.getData("select*from room where roomno='"+roomno+"'");
            
            while(rs.next()){
                txt_price.setText(rs.getString(4));  
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_Cmb_RoomNOActionPerformed

    private void btn_allteRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_allteRoomActionPerformed
        // Allot button click:
        
        int id =1;
        String name=txt_name.getText();
        String mobile=txt_mobNo.getText();
        String nationality=txt_nationality.getText();
        String gender=(String)Cmb_gender.getSelectedItem();
        String idproof=txt_ID.getText();
        String address=txt_Addres.getText();        
        String checkin=txt_checkInDate.getText();
        String email=txt_email.getText();
        String bed=(String)Cmb_Btype.getSelectedItem();
        String roomtype=(String)Cmb_RoomType.getSelectedItem();
        String roomno=(String)Cmb_RoomNO.getSelectedItem();
        String price=txt_price.getText(); 
        
        // -validations-
        if(name.equals("")){
            JOptionPane.showMessageDialog(null, "Name field cannot be empty");
            
        }else if(mobile.equals("")){
            JOptionPane.showMessageDialog(null, "Mobile No field cannot be empty");
            
        }else if(nationality.equals("")){
            JOptionPane.showMessageDialog(null, "Nationality field cannot be empty");
            
        }else if(idproof.equals("")){
            JOptionPane.showMessageDialog(null, "ID No field cannot be empty");
            
        }else if(address.equals("")){
            JOptionPane.showMessageDialog(null, "Address field cannot be empty");
            
        }else if(email.equals("")){
            JOptionPane.showMessageDialog(null, "E-mail field cannot be empty");
        }
        else{
            
            String Query="select max(id) from customer";
            try{
                ResultSet rs=selectdt.getData(Query);
            
                 while(rs.next())
                {    
                    id=rs.getInt(1);
                
                     id=id+1;
                
                        if(!price.equals(""))
                    {
                        Query="update room set status='Booked' where roomno='"+roomno+"'";
                        Insert_Update_Delete.setData(Query, "");
                        Query="insert into customer(id,name,mobileno,nationality,gender,email,nic,address,checkin,roomno,bed,roomtype,priceperday) values("+id+",'"+name+"','"+mobile+"','"+nationality+"','"+gender+"','"+email+"','"+idproof+"','"+address+"','"+checkin+"','"+roomno+"','"+bed+"','"+roomtype+"','"+price+"')";
                        Insert_Update_Delete.setData(Query,"Customer CheckIN successfully");
                        setVisible(false);
                        new customerChecking().setVisible(true);
                    }
                }
                 
                }catch(Exception e){
                    JOptionPane.showMessageDialog(null, e);
                }
        
            }
        

    }//GEN-LAST:event_btn_allteRoomActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(customerChecking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(customerChecking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(customerChecking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(customerChecking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new customerChecking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Cmb_Btype;
    private javax.swing.JComboBox<String> Cmb_RoomNO;
    private javax.swing.JComboBox<String> Cmb_RoomType;
    private javax.swing.JComboBox<String> Cmb_gender;
    private javax.swing.JButton btn_allteRoom;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_close;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txt_Addres;
    private javax.swing.JTextField txt_ID;
    private javax.swing.JTextField txt_checkInDate;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_mobNo;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_nationality;
    private javax.swing.JTextField txt_price;
    // End of variables declaration//GEN-END:variables
}
