
import javax.swing.JOptionPane;
import java.sql.*;
import project.selectdt;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author VIRAJ
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        btn_login = new javax.swing.JButton();
        btn_signup = new javax.swing.JButton();
        btn_forgtPasswrd = new javax.swing.JButton();
        txtPasswrd = new javax.swing.JPasswordField();
        btn_close = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(400, 200));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LOGIN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 79, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("E-mail");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 169, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 229, -1, -1));
        getContentPane().add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 169, 220, -1));

        btn_login.setBackground(new java.awt.Color(204, 255, 255));
        btn_login.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btn_login.setText("Login");
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        getContentPane().add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 319, -1, -1));

        btn_signup.setBackground(new java.awt.Color(255, 255, 204));
        btn_signup.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btn_signup.setText("Siign Up");
        btn_signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_signupActionPerformed(evt);
            }
        });
        getContentPane().add(btn_signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 319, -1, -1));

        btn_forgtPasswrd.setBackground(new java.awt.Color(204, 204, 255));
        btn_forgtPasswrd.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btn_forgtPasswrd.setText("Forgot password?");
        btn_forgtPasswrd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_forgtPasswrdActionPerformed(evt);
            }
        });
        getContentPane().add(btn_forgtPasswrd, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 319, -1, -1));
        getContentPane().add(txtPasswrd, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 229, 220, -1));

        btn_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel_25px.png"))); // NOI18N
        btn_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_closeActionPerformed(evt);
            }
        });
        getContentPane().add(btn_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(608, 11, 29, 26));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/01.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_closeActionPerformed
                int a=JOptionPane.showConfirmDialog(null, "Are you really want to close","Select",JOptionPane.YES_NO_OPTION);
        if(a==0)
            System.exit(0);
        
    }//GEN-LAST:event_btn_closeActionPerformed

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
            
            int check=0;
            String email=txt_email.getText();
            String password=txtPasswrd.getText();
            
            if(email.equals("")||password.equals("")){
                check=1;
                JOptionPane.showMessageDialog(null,"Both fields are required");
                
            }
            else if(password.equals(""))
            {
                    check=1;
                    JOptionPane.showMessageDialog(null,"password must be filled");
            }
            else if(email.equals("admin") && password.equals("123")){
                
                check=1;
     
                setVisible(false);
                new adminHome().setVisible(true);
            }
            else
            {
                ResultSet rs=selectdt.getData("select*from users where email='"+email+"' and password='"+password+"' ");
                try{
                    if(rs.next())
                    {
                        check=1;
                        if(rs.getString(7).equals("true"))
                        {
                            setVisible(false);
                            new home().setVisible(true);
                        }
                        else
                        {
                             JOptionPane.showMessageDialog(null,"Wait for Admin approval");
                        }
                    }
                    
                }
                catch(Exception e)
                {
                     JOptionPane.showMessageDialog(null,e);
                }

            } 
            if(check==0){
                    JOptionPane.showMessageDialog(null,"Incorrect email or password");
                }
            
    }//GEN-LAST:event_btn_loginActionPerformed

    private void btn_signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_signupActionPerformed
        setVisible(false);
        new Sighup().setVisible(true);
    }//GEN-LAST:event_btn_signupActionPerformed

    private void btn_forgtPasswrdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_forgtPasswrdActionPerformed
        setVisible(false);
         new forgotpassword().setVisible(true);
    }//GEN-LAST:event_btn_forgtPasswrdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_close;
    private javax.swing.JButton btn_forgtPasswrd;
    private javax.swing.JButton btn_login;
    private javax.swing.JButton btn_signup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField txtPasswrd;
    private javax.swing.JTextField txt_email;
    // End of variables declaration//GEN-END:variables
}
