import project.*;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import java.util.regex.*;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author VIRAJ
 */
public class manageroom extends javax.swing.JFrame {

    /**
     * Creates new form manageroom
     */
    public manageroom() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_close = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtRoom_no = new javax.swing.JTextField();
        txt_Price = new javax.swing.JTextField();
        Cmb_Rtype = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        Cmb_btytpe = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        btn_add = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(200, 200));
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MANAGE ROOM");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 24, -1, -1));

        btn_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel_25px.png"))); // NOI18N
        btn_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_closeActionPerformed(evt);
            }
        });
        getContentPane().add(btn_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(937, 0, 30, 30));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Room No", "Room Type", "Bed Type", "Price", "Status"
            }
        ));
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 99, 540, 299));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Room No");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(661, 86, 65, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Room Type");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(661, 148, -1, -1));

        txtRoom_no.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        txtRoom_no.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRoom_noKeyTyped(evt);
            }
        });
        getContentPane().add(txtRoom_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(661, 108, 224, -1));

        txt_Price.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        txt_Price.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_PriceKeyTyped(evt);
            }
        });
        getContentPane().add(txt_Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(661, 318, 224, -1));

        Cmb_Rtype.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Cmb_Rtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "Non-AC" }));
        getContentPane().add(Cmb_Rtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(661, 176, 224, 30));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Bed Type");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(661, 219, -1, -1));

        Cmb_btytpe.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Cmb_btytpe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Double", "Triple" }));
        getContentPane().add(Cmb_btytpe, new org.netbeans.lib.awtextra.AbsoluteConstraints(661, 243, 224, 30));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Price");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(661, 296, -1, -1));

        btn_add.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btn_add.setText("Add ");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });
        getContentPane().add(btn_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(736, 372, 86, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/spacejoy-tAuc4H7Qf9s-unsplash.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_closeActionPerformed
        int a=JOptionPane.showConfirmDialog(null, "Are you really want to close","Select",JOptionPane.YES_NO_OPTION);
        
        if(a==0){setVisible(false);
            new home().setVisible(true);
        }
        else{setVisible(true);
        }
        
        
        
    }//GEN-LAST:event_btn_closeActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        
        String roomNo=txtRoom_no.getText();
        String roomType=(String)Cmb_Rtype.getSelectedItem();
        String Bed=(String)Cmb_btytpe.getSelectedItem();
        String Price=txt_Price.getText();
        
        if(roomNo.equals("")){
            JOptionPane.showMessageDialog(null, "Room no cannot be blank");
        }
//        else if(roomType.equals("")){
//            JOptionPane.showMessageDialog(null, "Room Type cannot be blank");
//        }
//        else if(Bed.equals("")){
//            JOptionPane.showMessageDialog(null, "Bed Type cannot be blank");
//        }
        else if(Price.equals("")){
            JOptionPane.showMessageDialog(null, " Price value cannot be blank");
        }
        else{                  
        String Query="insert into room values('"+roomNo+"','"+roomType+"','"+Bed+"','"+Price+"','Not Booked')";
        Insert_Update_Delete.setData(Query, "Successfully Updated");
        setVisible(false);
        new manageroom().setVisible(true);
        }      
    }//GEN-LAST:event_btn_addActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        
        ResultSet rs=selectdt.getData("select*from room");
        DefaultTableModel model=(DefaultTableModel)table.getModel();
        
        try{
            while(rs.next())
            {
                model.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5)}); 
            }
            rs.close();
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_formComponentShown
//key typed event
    private void txtRoom_noKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRoom_noKeyTyped
        char c=evt.getKeyChar();
        
        if(!Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_txtRoom_noKeyTyped
//key typed event
    private void txt_PriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_PriceKeyTyped
        char c=evt.getKeyChar();
        
        if(!Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_txt_PriceKeyTyped
 
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(manageroom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(manageroom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(manageroom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(manageroom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new manageroom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Cmb_Rtype;
    private javax.swing.JComboBox<String> Cmb_btytpe;
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_close;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtRoom_no;
    private javax.swing.JTextField txt_Price;
    // End of variables declaration//GEN-END:variables
}
