
import javax.swing.JOptionPane;
import project.Insert_Update_Delete;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author VIRAJ
 */
public class Sighup extends javax.swing.JFrame {

    /**
     * Creates new form sighup
     */
    public Sighup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        txt_passwrd = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Cmb_SecQuestion = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txt_answer = new javax.swing.JTextField();
        txt_adress = new javax.swing.JTextField();
        btn_forgotPasswrd = new javax.swing.JButton();
        btn_login = new javax.swing.JButton();
        btn_signUp = new javax.swing.JButton();
        btn_close = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setLocation(new java.awt.Point(300, 100));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(761, 540));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SIGN UP");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 171, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("E-,mail");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 202, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Password");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 239, -1, -1));

        txt_name.setBackground(new java.awt.Color(204, 204, 204));
        txt_name.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_name.setForeground(new java.awt.Color(51, 51, 51));
        txt_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nameKeyTyped(evt);
            }
        });
        getContentPane().add(txt_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 270, -1));

        txt_email.setBackground(new java.awt.Color(204, 204, 204));
        txt_email.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_email.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 200, 275, -1));

        txt_passwrd.setBackground(new java.awt.Color(204, 204, 204));
        txt_passwrd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_passwrd.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(txt_passwrd, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 237, 275, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Security Question");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 287, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Answer");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 326, -1, -1));

        Cmb_SecQuestion.setBackground(new java.awt.Color(204, 204, 204));
        Cmb_SecQuestion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Cmb_SecQuestion.setForeground(new java.awt.Color(51, 51, 51));
        Cmb_SecQuestion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "What elementary school dd you attended?", "What is your first car?", "What is the name of your pet?", "What is your born city/town?" }));
        getContentPane().add(Cmb_SecQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 282, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Address");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 363, -1, -1));

        txt_answer.setBackground(new java.awt.Color(204, 204, 204));
        txt_answer.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_answer.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(txt_answer, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 324, 275, -1));

        txt_adress.setBackground(new java.awt.Color(204, 204, 204));
        txt_adress.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_adress.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(txt_adress, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 361, 275, -1));

        btn_forgotPasswrd.setBackground(new java.awt.Color(255, 255, 255));
        btn_forgotPasswrd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_forgotPasswrd.setForeground(new java.awt.Color(0, 0, 0));
        btn_forgotPasswrd.setText("Forgot Password ?");
        btn_forgotPasswrd.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_forgotPasswrd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_forgotPasswrdActionPerformed(evt);
            }
        });
        getContentPane().add(btn_forgotPasswrd, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 440, -1, -1));

        btn_login.setBackground(new java.awt.Color(255, 255, 255));
        btn_login.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_login.setForeground(new java.awt.Color(0, 0, 0));
        btn_login.setText("Login");
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        getContentPane().add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 436, -1, -1));

        btn_signUp.setBackground(new java.awt.Color(255, 255, 255));
        btn_signUp.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_signUp.setForeground(new java.awt.Color(0, 0, 0));
        btn_signUp.setText("Sign Up");
        btn_signUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_signUpActionPerformed(evt);
            }
        });
        getContentPane().add(btn_signUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 436, -1, -1));

        btn_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel_25px.png"))); // NOI18N
        btn_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_closeActionPerformed(evt);
            }
        });
        getContentPane().add(btn_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 0, 30, 30));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/abstract-luxury-gradient-blue-background-smooth-dark-blue-withhh.jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_signUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_signUpActionPerformed

        // TODO add your handling code here:
        String name=txt_name.getText();
        String email=txt_email.getText();
        String password=txt_passwrd.getText();
        String securityQuestion=(String)Cmb_SecQuestion.getSelectedItem();
        String answer=txt_answer.getText();
        String address=txt_adress.getText();
        
//        if(name.){
//            
//        }
        if(name.equals("")||email.equals("")||password.equals("")||securityQuestion.equals("")||answer.equals("")||address.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Fill All fields");
        }
        else{
            String Query;
            Query="insert into users values('"+name+"','"+email+"','"+password+"','"+securityQuestion+"','"+answer+"','"+address+"','false')";
            Insert_Update_Delete.setData(Query, "Registerd successfully");
            setVisible(false);
            new Sighup().setVisible(true);
        }
        
    }//GEN-LAST:event_btn_signUpActionPerformed

    private void btn_forgotPasswrdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_forgotPasswrdActionPerformed
        setVisible(false);
         new forgotpassword().setVisible(true);
    }//GEN-LAST:event_btn_forgotPasswrdActionPerformed

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        setVisible(false);
        new login().setVisible(true);
    }//GEN-LAST:event_btn_loginActionPerformed

    private void btn_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_closeActionPerformed
        
        
        int a=JOptionPane.showConfirmDialog(null, "Do you really want to close","Select",JOptionPane.YES_NO_OPTION);
        if(a==0){
            System.exit(0);
    }//GEN-LAST:event_btn_closeActionPerformed
    }
    private void txt_nameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nameKeyTyped
        
        char c=evt.getKeyChar();
        
        if(!Character.isLetter(c)){
            evt.consume();
        }
    }//GEN-LAST:event_txt_nameKeyTyped
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sighup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sighup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sighup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sighup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sighup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Cmb_SecQuestion;
    private javax.swing.JButton btn_close;
    private javax.swing.JButton btn_forgotPasswrd;
    private javax.swing.JButton btn_login;
    private javax.swing.JButton btn_signUp;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txt_adress;
    private javax.swing.JTextField txt_answer;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_name;
    private javax.swing.JPasswordField txt_passwrd;
    // End of variables declaration//GEN-END:variables
}
